o3de/community

community-membership.md

- Move requests to the approving SIG's repo
- Ask for an Issue to be filed instead of a PR

Clarify reviewer/maintainer requests

---

committee/committee-marketing/proposals/example.md
committee/committee-marketing/readme.md

iniital checkin of agenda for 9/23

---

committee/committee-marketing/proposals/example.md
committee/committee-marketing/proposals/index.md
committee/committee-marketing/proposals/reading-list.md

changed file names and added reading list

---

committee/committee-marketing/readme.md

update to agenda for time

---

committee/committee-marketing/readme.md

added notes

---

committee/committee-marketing/meeting-notes/meeting-agenda-2021-10-4.md
committee/committee-marketing/meeting-notes/meeting-agenda-2021-9-23.md
committee/committee-marketing/readme.md

Added planned agenda for 10-4-2021 meeting

---

committee/committee-marketing/meeting-notes/meeting-agenda-2021-10-4.md

Notes from 10/4 marketing committee meeting

---

values.md

Corrected the take a break value heading
Signed-off-by: Amy Marrich (spotz) <amy@demarco.com>

Corrected grammar typo in values.md

---

features/sigjson/sig-content-features.json

Signed-off-by: Tom Hulton-Harrop <82228511+hultonha@users.noreply.github.com>
Big shout-out to @amzn-jillich and @amzn-rhhong for their help compiling this list 😄

add animation features to sig-content feature matrix

---

features/sigjson/sig-core-features.json

Signed-off-by: Pratik Patel <pratikpa@amazon.com>

Updated with core features managed by SIG-Core

---

features/sigjson/sig-build-features.json

This is to scope out the features that SIG-Build is responsible for. Load this json file into this form to see the status values: https://o3de.github.io/community/features/form.html
Signed-off-by: Mike Chang <changml@amazon.com>

Initial featureset for Build and Infra

---

features/sigjson/sig-graphics-audio-features.json

Signed-off-by: mcphedar <mcphedar@amazon.com>

Adding Audio subsystems

---

O3DE Elections/O3DE Elections Guide.md
O3DE Elections/README.md

Created folder for O3DE Elections Content 
Created Guide for the O3DE Elections for anyone looking to host an election to follow.

Created Election Folder and Guide

---

committee/committee-marketing/meeting-notes/meeting-agenda-2022-01-10.md
committee/committee-marketing/readme.md

Update marketing committee dashboard with 21.11 release products and outside articles.
Add 21.11.2 release.
Signed-off-by: Jonathan Capes <j.capes@gmail.com>

Add 21.11 info and 01-10-2022 meeting

---

features/sigjson/sig-core-features.json

resolves o3de/o3de#12006
Signed-off-by: lumberyard-employee-dm <56135373+lumberyard-employee-dm@users.noreply.github.com>

Updated the Sig-Core Features JSON for the 2022 October release

---

features/sigjson/sig-network-features.json

Update the SIG/Network feature matrix
* Added new remote tools section
* Updated content information
* Added extra documentation links
See https://github.com/o3de/o3de/issues/12036
Signed-off-by: Pip Potter <61438964+lmbr-pip@users.noreply.github.com>

Update SIG/Network feature matrix

---

Migration Guides/Lumberyard to O3DE/EMFX/README.md
Migration Guides/Lumberyard to O3DE/Misc-Documents/Lumberyard-Features/README.md
Migration Guides/Lumberyard to O3DE/Misc-Documents/Scripts/README.md
Migration Guides/Lumberyard to O3DE/Misc-Documents/Tutorials/Converting-a-Legacy-Renderer-Project-to-an-Atom-Project/README.md
Migration Guides/Lumberyard to O3DE/Networking/README.md
Migration Guides/Lumberyard to O3DE/README.md

Updated Various Docs links, missing Data, formatting issues and prefab section on main readme.

Ly migration update

---

README.md
markdown/github-markdown/README.md

Added markdown Document. 
Added links to this document in the main readme on the repository. 
This document is created to assist anyone who may be looking to update existing files on GitHub or create new one. It will help SIG chairs keep their repositories up-to-date and use the proper formatting along with show the types available. 

Initial GitHub markdown update

---

process-docs-and-markdown/discord-permissions.md

Created Discord permissions Doc

Created Discord Permissions Doc

---

process-docs-and-markdown/discord-moderation-guidelines.md

Creation of the initial post of the Moderation Guidelines. 
Need to add table and fix formatting.

Initial Creation of Moderation Guidelines

---

O3DE Elections/O3DE Elections Guide.md
O3DE Elections/README.md

Election update

---

process-docs-and-markdown/discord-setup.md

Created Document for setting up a discord from scratch.

Creating a Discord Server

---

process-docs-and-markdown/discord-moderation-guidelines-Quiz.md

Initial creation of Moderation Guidelines Quiz.

Creation of Moderation Guidelines Quiz

---

process-docs-and-markdown/discord-tips-tricks-troubleshooting.md

Added Tips and Tricks Document

---

process-docs-and-markdown/blog-process.md

Created Blog process guide

---

process-docs-and-markdown/promotion-and-demotion-guidelines.md

Creation of the Promotion & Demotion Guidelines for the Moderation Guidelines Document.

Created Promotion and Demotion Guidelines

---

process-docs-and-markdown/README.md

Created Readme file

---

process-docs-and-markdown/github-markdown.md

Created GitHub Markdown Cheat sheet.

Created GitHub markdown Cheat-sheet
